# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        base_de_datos:
            entity:
                class: AppBundle\Entity\User
                property: loginUsername

    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_DEPARTMENT_HEAD, ROLE_FINANCIAL_MANAGER]
        ROLE_DEPARTMENT_HEAD: [ROLE_GROUP_TUTOR]
        ROLE_GROUP_TUTOR: [ROLE_EDUCATIONAL_TUTOR]
        ROLE_EDUCATIONAL_TUTOR: [ROLE_WORK_TUTOR]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: usuario_entrar
                check_path: usuario_entrar

            logout:
                path: usuario_salir